-- MySQL Script generated by MySQL Workbench
-- Wed Feb  7 13:21:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FinanceDBSchema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FinanceDBSchema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FinanceDBSchema` DEFAULT CHARACTER SET utf8 ;
USE `FinanceDBSchema` ;

-- -----------------------------------------------------
-- Table `FinanceDBSchema`.`userLogin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinanceDBSchema`.`userLogin` (
  `email` VARCHAR(45) NOT NULL,
  `passwordHash` VARCHAR(45) NOT NULL,
  `passwordSalt` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`email`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinanceDBSchema`.`userData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinanceDBSchema`.`userData` (
  `FirstName` VARCHAR(56) NOT NULL,
  `LastName` VARCHAR(56) NOT NULL,
  `userID` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `maritalStatus` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userID`),
  INDEX `email_idx` (`email` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  FULLTEXT INDEX `maritalStatus` (`maritalStatus`) VISIBLE,
  CONSTRAINT `email`
    FOREIGN KEY (`email`)
    REFERENCES `FinanceDBSchema`.`userLogin` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinanceDBSchema`.`hashTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinanceDBSchema`.`hashTable` (
  `hashKey` INT NOT NULL,
  `algorithimName` VARCHAR(45) NULL,
  PRIMARY KEY (`hashKey`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinanceDBSchema`.`financeData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinanceDBSchema`.`financeData` (
  `financeID` INT NOT NULL AUTO_INCREMENT,
  `monthylExpenses` DECIMAL(12) NULL,
  `monthlyIncome` DECIMAL(12) NULL,
  `dependents` INT NOT NULL,
  `numberOfDependents` INT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`financeID`),
  INDEX `email_idx` (`email` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `email`
    FOREIGN KEY (`email`)
    REFERENCES `FinanceDBSchema`.`userLogin` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinanceDBSchema`.`stateTaxTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinanceDBSchema`.`stateTaxTable` (
  `stateId` INT NOT NULL AUTO_INCREMENT,
  `stateTax` DECIMAL(12) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `incomeLowBound` FLOAT NOT NULL,
  `incomeHighBound` FLOAT NOT NULL,
  `maritalStatus` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`stateId`),
  INDEX `maritailstatus_idx` (`maritalStatus` ASC) VISIBLE,
  CONSTRAINT `maritailstatus`
    FOREIGN KEY (`maritalStatus`)
    REFERENCES `FinanceDBSchema`.`userData` (`maritalStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinanceDBSchema`.`federalTaxTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FinanceDBSchema`.`federalTaxTable` (
  `federalId` INT NOT NULL AUTO_INCREMENT,
  `federalTax` DECIMAL(12) NOT NULL,
  `incomeLowBound` FLOAT NOT NULL,
  `incomeHighBound` FLOAT NOT NULL,
  `maritalStatus` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`federalId`),
  INDEX `maritalStatus_idx` (`maritalStatus` ASC) VISIBLE,
  CONSTRAINT `maritalStatus`
    FOREIGN KEY (`maritalStatus`)
    REFERENCES `FinanceDBSchema`.`userData` (`maritalStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
