POST http://localhost:3200/form/postDetails
content-type: application/json

{
  "FirstName": "george",
  "LastName": "bush",
  "Year": 2004,
  "Maritalstatus": "Married",
  "State": "DC",
  "AGI": 10000000.0,
  "AME": 10000.0,
  "NumDependents": 2,
  "FinGoal": 10,
  "Dependents": true,
  "Email": "georgebush"
}