POST http://localhost:3200/form/postDetails
content-type: application/json

{
  "FirstName": "Colton",
  "LastName": "Williams",
  "Year": 2023,
  "Maritalstatus": "Single",
  "State": "WI",
  "AGI": 10000.0,
  "AME": 500.0,
  "NumDependents": 0,
  "FinGoal": 1000000,
  "Dependents": false,
  "Email": "coltoniscool"
}